.. |new_manual.introduction.chapter_num|              replace:: **Chapter 1**
.. |new_manual.transform.chapter_num|                 replace:: **Chapter 2**
.. |new_manual.transform_in_parallel.chapter_num|     replace:: **Chapter 3**
.. |new_manual.originate.chapter_num|                 replace:: **Chapter 4**
.. |new_manual.pipeline_printout.chapter_num|         replace:: **Chapter 5**
.. |new_manual.cmdline.chapter_num|                   replace:: **Chapter 6**
.. |new_manual.pipeline_printout_graph.chapter_num|   replace:: **Chapter 7**
.. |new_manual.output_file_names.chapter_num|         replace:: **Chapter 8**
.. |new_manual.task_completion.chapter_num|           replace:: **Chapter 9**
.. |new_manual.decorators_compendium.chapter_num|     replace:: **Chapter 10**  
.. |new_manual.split.chapter_num|                     replace:: **Chapter 11**  
.. |new_manual.merge.chapter_num|                     replace:: **Chapter 12**  

